#!/bin/bash

CONSUL_HOST='192.168.42.13:8500'

curl -sL $CONSUL_HOST/v1/agent/service/deregister/admin-1
curl -sL $CONSUL_HOST/v1/agent/service/deregister/www-1
curl -sL $CONSUL_HOST/v1/agent/service/deregister/www-2
