#!/bin/bash

CONSUL_HOST='192.168.42.13:8500'

python simple-web.py 8081 > /dev/null &
python simple-web.py 8082 > /dev/null &
python simple-web.py 8083 > /dev/null &

curl -d '{
    "ID": "app-instance-1",
     "Name": "www",
     "Tags": [ "website", "prod"],
     "Address": "127.0.0.1",
     "Port": 8081,
     "Check": {
        "HTTP": "http://127.0.0.1:8081",
        "Interval": "2s"
      }
}' -X PUT http://$CONSUL_HOST/v1/agent/service/register

curl -d '{
    "ID": "app-instance-2",
     "Name": "www",
     "Tags": [ "website", "prod"],
     "Address": "127.0.0.1",
     "Port": 8082,
     "Check": {
        "HTTP": "http://127.0.0.1:8082",
        "Interval": "2s"
      }
}' -X PUT http://$CONSUL_HOST/v1/agent/service/register

curl -d '{
    "ID": "admin-1",
     "Name": "admin",
     "Tags": [ "admin", "prod"],
     "Address": "127.0.0.1",
     "Port": 8083,
     "Check": {
        "HTTP": "http://127.0.0.1:8083",
        "Interval": "2s"
      }
}' -X PUT http://$CONSUL_HOST/v1/agent/service/register

./haproxy-consul-template
