#!/bin/bash

CONSUL_HOST=192.168.42.13:8500

echo "setting redis_host"

curl -s -X PUT -d 'my-redis-host.redis-saas-provider.com' http://$CONSUL_HOST/v1/kv/test/redis_host

echo ""
echo ""

echo "setting db_host"

curl -X PUT -d 'my-db-host.db-saas-provider.com' http://$CONSUL_HOST/v1/kv/test/db_host

echo ""
echo ""

echo "getting a value is easy, too!"

DB_HOST=`curl -sL http://$CONSUL_HOST/v1/kv/test/db_host?raw`
REDIS_HOST=`curl -sL http://$CONSUL_HOST/v1/kv/test/redis_host?raw`
echo "db_host is $DB_HOST and redis_host is $REDIS_HOST"

echo ""
echo ""
echo "setting some values for haproxy"
RES=`curl -s -X PUT -d '6' http://$CONSUL_HOST/v1/kv/haproxy/retries`
echo ""
RES=`curl -s -X PUT -d '8192' http://$CONSUL_HOST/v1/kv/haproxy/maxconn `
